### ISSUE TITLE
Dockerfile Kafka version points to non existing http address

### ISSUE THREAD

**Issue by Wicked-Creations** [IBM/kraft-mode-kafka-on-kubernetes#1]
Dockerfile: 
ENV KAFKA_VERSION=2.8.0

The Dockerfile refers to Kafka version 2.8.0. which in turn tries to pars it in an URL that would be non existing.

**Comment by vuldin** [comment]
Ahh, thanks so much for this catch @Wicked-Creations ! It looks like version 2.8.0 was removed entirely.
